CREATE  TABLE USER (EMPID VARCHAR2(50) NOT NULL,ACCESSKEY VARCHAR2(50),COUNTRY VARCHAR2(50));

CREATE  TABLE TEAMHIERARCHY (EMPID VARCHAR2(50) NOT NULL, MANAGERID VARCHAR2(50) NOT NULL);

CREATE  TABLE USERACCESS (EMPID VARCHAR2(50) NOT NULL, ACCESSKEY VARCHAR2(50), COUNTRY VARCHAR2(50), SUBUSER VARCHAR2(50), SUBUSER_ACCESSKEY VARCHAR2(50) , SUBUSER_COUNTRY VARCHAR2(50));

INSERT INTO USER VALUES ('MILLER', 'TRMLR', 'SG'); 
INSERT INTO USER VALUES ('TESSA', 'TRTSSA', 'SG'); 
INSERT INTO USER VALUES ('DOSSON', 'TRDSSN', 'HK'); 
INSERT INTO USER VALUES ('RICKY', 'TRRCKY', 'SG'); 
INSERT INTO USER VALUES ('AARON', 'TRARON', 'SG'); 
INSERT INTO USER VALUES ('BOB', 'TRBOB', 'HK'); 

INSERT INTO TEAMHIERARCHY VALUES ('TESSA', 'MILLER'); 
INSERT INTO TEAMHIERARCHY VALUES ('DOSSON', 'MILLER'); 
INSERT INTO TEAMHIERARCHY VALUES ('RICKY', 'TESSA'); 
INSERT INTO TEAMHIERARCHY VALUES ('AARON', 'TESSA'); 
INSERT INTO TEAMHIERARCHY VALUES ('BOB', 'DOSSON'); 

DROP ALIAS IF EXISTS INSERT_USERACCESS_DATA;
CREATE ALIAS INSERT_USERACCESS_DATA(IN EMPID VARCHAR2)

BEGIN
  DECLARE 
  I VARCHAR(50);
  LP NUMBER;
  TYPE TB IS RECORD (U_ID VARCHAR2(100),U_KEY VARCHAR2(100),U_CNT VARCHAR2(100),
  SU_ID VARCHAR2(100),SU_KEY VARCHAR2(100),SU_CNT VARCHAR2(100));
  TYPE TB1 IS TABLE OF TB INDEX BY BINARY_INTEGER;    
  TB2 TB1;
  TB3 TB1;
  J NUMBER;
  K NUMBER;
  L NUMBER;
  BEGIN
    I :='MILLER';
    J :=1;
    TB2(J).U_ID := I;
  FOR C IN (SELECT COUNT(*) OVER(),TH.EMPID,SU.ACCESSKEY,SU.COUNTRY FROM TEAMHIERARCHY TH,USER SU  WHERE TH.MANAGER_ID = I AND SU.EMPID = TH.EMPID)
  LOOP 
    J := J+1;
  TB2(J).U_ID  := C.EMPID;
  FOR C1 IN (SELECT  EMPID FROM TEAMHIERARCHY WHERE MANAGER_ID = C.EMPID)
  LOOP  
  J := J+1;
  TB2(J).U_ID  := C1.EMPID;
  END LOOP;
  END LOOP;     
  FOR K IN 1..J LOOP
     SELECT B1.EMPID,B1.ACCESSKEY,B1.COUNTRY,B2.EMPID SB_USER,B2.ACCESSKEY SB_AK,B1.COUNTRY SB_CNT
     INTO TB3(K).U_ID,TB3(K).U_KEY,TB3(K).SU_CNT,TB3(K).SU_ID,TB3(K).SU_KEY,TB3(K).SU_CNT
  FROM 
  (SELECT EMPID,ACCESSKEY,COUNTRY FROM USER WHERE EMPID = I) B1,
  (SELECT EMPID,ACCESSKEY,COUNTRY FROM USER WHERE EMPID = TB2(K).U_ID) B2; 
          END LOOP;
FOR L IN 1..J LOOP
INESRT INTO USERACCESS VALUES (TB3(L).U_ID,TB3(L).U_KEY,TB3(L).U_CNT,TB3(L).SU_ID,TB3(L).SU_KEY,TB3(L)S.U_CNT);
END LOOP;          
   END;